### ISSUE TITLE
Can multiple keys be sent with one button?

### ISSUE THREAD

**Issue by thehauntedmattress** [nitaybz/homebridge-samsung-remote#7]
Can I program a switch in Homekit to send a series of keys?  Is that possible now or will it be possible in the future?

**Comment by tavicu** [comment]
I've sent a pull request. Let's see what @nitaybz says :)

#8

**Comment by thehauntedmattress** [comment]
Also on a different note: is it possible to make volume control and mute a lightbulb type homekit switch?

**Comment by nitaybz** [comment]
"on a different note" should be opened in a new issue :)
but anyway, it can't be as a bulb type since it's not possible to get the status of the volume from the tv... so if you change it once manually it will be out of sync...

@tavicu your pull request looks good, thanks for that :) don't have the time to test it so I'll count on you that it works...

**Comment by tavicu** [comment]
Hei @nitaybz,

I wanted to make some changes on your repo again because sometimes the state of the TV is not the correct one but the most important one was that when the tv is off, it takes almost 5 seconds to update the state because of the dependence you are using and it also delay all of my other accessories.

Unfortunately that repo is not existing anymore so i was not able to send a pull request there to fix it

I hope you don’t mind but i’ve made a new repo where i fixed a lot of things and bring some new features. If you want, take a look, maybe you find something interesting: https://github.com/tavicu/homebridge-samsung-tizen
